# Generated by Django 2.2.16 on 2022-03-05 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Ник пользователя', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Ник должен быть комбинацией букв,цифр и символов @.+-_', regex='^[\\w.@+-]+')], verbose_name='Логин'),
        ),
    ]
