# Generated by Django 2.2.16 on 2022-03-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',)},
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, help_text='Код подтверждения', max_length=9, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, help_text='Пароль', max_length=128, null=True, verbose_name='Пароль'),
        ),
    ]
