# Generated by Django 2.2.16 on 2022-03-04 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, help_text='Пароль', max_length=128, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Ник пользователя', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Ник должен быть комбинацией букв,цифр и символов @.+-_', regex='^[\\w.@+-]+')], verbose_name='Логин'),
        ),
    ]
