# Generated by Django 2.2.16 on 2022-03-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220304_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='Фамилия пользователя', max_length=150, null=True, verbose_name='Фамилия'),
        ),
    ]
