# Generated by Django 2.2.16 on 2022-03-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220311_1433'),
        ('users', '0005_auto_20220311_1000'),
    ]

    operations = [
    ]
