# Generated by Django 2.2.16 on 2022-03-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20220312_2139'),
        ('users', '0006_merge_20220312_2030'),
    ]

    operations = [
    ]
