# Generated by Django 2.2.16 on 2022-03-02 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование категории')),
                ('slug', models.SlugField(choices=[('Books', 'Книги'), ('Films', 'Фильмы'), ('Music', 'Музыка'), ('', 'ANY_one'), ('', 'ANY_two')], unique=True, verbose_name='Уникальный адрес категории')),
            ],
            options={
                'verbose_name': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование жанра')),
                ('slug', models.SlugField(choices=[('Fairytale', 'Сказка'), ('Rock', 'Рок'), ('ArtHouse', 'Артхаус'), ('', 'ANY_one'), ('', 'ANY_two')], unique=True, verbose_name='Уникальный адрес жанра')),
            ],
            options={
                'verbose_name': 'Жанры',
            },
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'verbose_name': 'Произведения'},
        ),
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='reviews.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='genre', to='reviews.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='rating',
            field=models.IntegerField(help_text='Введите текст поста', verbose_name='Рейтинг поста'),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
    ]
