# Generated by Django 2.2.16 on 2022-03-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220311_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretitle',
            options={'ordering': ('genre',), 'verbose_name': 'Жанры_произведений'},
        ),
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(help_text='Введите текст поста', null=True, verbose_name='Рейтинг поста'),
        ),
    ]
